name: g_sui_hunter
description: チャレキャラ2020：コレステローラーズ

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  provider: ^4.3.2+2
  firebase_core: ^0.5.2+1
  firebase_auth: ^0.18.3+1
  cloud_firestore: ^0.14.3+1
  google_sign_in: ^4.5.1
  decoratable_text: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
